M48
; DRILL file {KiCad 7.0.8} date Mon Nov  6 16:26:25 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-06T16:26:25-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X180.5Y-92.505
X180.5Y-97.505
T2
X145.54Y-88.35
X145.54Y-91.35
T3
X146.25Y-71.5
X146.25Y-123.5
X182.25Y-71.5
X182.25Y-123.5
T0
M30
